apiVersion: 1
datasources:
  - name: LocalStack-CloudWatch
    type: cloudwatch
    jsonData:
      authType: keys
      defaultRegion: us-east-1
      endpoint: http://localstack:4566
    secureJsonData:
      accessKey: test
      secretKey: test
    editable: true